<?php
/**
* Ifthenpay_Multibanco module dependency
*
* @category    Ifthenpay
* @package     Ifthenpay_Multibanco
* @author      Manuel Rocha
* @copyright   Ifthenpay (http://www.ifthenpay.com)
* @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/

/**
 * @var \Magento\Paypal\Block\Checkout\Onepage\Success\BillingAgreement $block
 */


?>
<div>
<table style="width: 300px; margin: 0 auto;">
  <tbody>
    <tr>
      <td colspan="2" style="text-align: center;border-bottom: 1px solid black;font-weight: bold; font-size: 13px;">
        Pagamento por Multibanco ou Homebanking
        <br />
        <img src="<?php echo $block->getViewFileUrl('Ifthenpay_Multibanco::images/multibanco.jpg')?>" style="width: 100px;" />
      </td>
    </tr>
    <tr>
      <td>
        Entidade
      </td>
      <td style="text-align: right;font-weight: bold;">
        <?php echo $block->getEntidade(); ?>
      </td>
    </tr>
    <tr>
      <td>
        Referencia
      </td>
      <td style="font-weight: bold;text-align: right;">
        <?php echo $block->getReferenciaFront(true); ?>
      </td>
    </tr>
    <tr>
      <td>
        Valor
      </td>
      <td style="font-weight: bold;text-align: right;">
        <?php echo $block->getValorFront(); ?>
      </td>
    </tr>
    <tr>
      <td colspan="2" style="text-align: center;font-weight: bold;border-top: 1px solid black; font-size: 7px;">
        O talao emitido pela caixa automatica faz prova de pagamento. Conserve-o.
      </td>
    </tr>
  </tbody>
</table>
</div>
