<?php
/**
* Ifthenpay_Multibanco module dependency
*
* @category    Gateway Payment
* @package     Ifthenpay_Multibanco
* @author      Manuel Rocha
* @copyright   Manuel Rocha (http://www.manuelrocha.biz)
* @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/

?>
<div class="payflow-settings-notice">
    <strong class="important-label">Instruções Callback:</strong>
    <p>Para ativar o callback deverá comunicar à Ifthenpay os seguintes elementos:</p>
    <ul class="options-list">
        <li><strong>Entidade: <span style="color:blue;"><?php echo $block->getEntidade(); ?></span></strong></li>
        <li><strong>Subentidade: <span style="color:blue;"><?php echo $block->getSubentidade(); ?></span></strong></li>
        <li><strong>4 últimos dígitos da chave de backoffice</strong> (chave fornecida no ato da adesão continuida por 16 dígitos numéricos agrupados 4 a 4 com o seguinte formarto <strong>0000-0000-0000-0000</strong>)</li>
        <li><strong>Url de Callback: <span style="color:blue;"><?php echo $block->getUrlCallback(); ?></span></strong></li>
        <li><strong>Chave Anti-phishing: <span style="color:blue;"><?php echo $block->getAntiPhishingKey(); ?></span></strong></li>
    </ul>
    <p>Estes elementos deverão ser comunicados para o email <a href="mailto:callback@ifthenpay.com" target="_blank">callback@ifthenpay.com</a> com o assunto 'Ativar Callback'</p>
    <strong class="important-label">NOTA:</strong>
    <p>Não serão aceites print screens desta página. A informação deverá ser copiada e colado no email.</p>
</div>
